import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
// Immediately override require and module loading before any code runs
(function() {
  'use strict';
  const nodeModulesToStub = ['stream', 'readable-stream', 'fs', 'path', 'util', 'events', 'buffer', 'base64'];
  const requireCache = {};
  
  function shouldStub(id) {
    if (!id) return false;
    const moduleName = String(id).split('/')[0].split('@').pop();
    return nodeModulesToStub.includes(moduleName) || nodeModulesToStub.includes(id);
  }
  
  function getStub(id) {
    if (!requireCache[id]) {
      requireCache[id] = {};
    }
    return requireCache[id];
  }
  
  // Override require if it exists
  if (typeof require !== 'undefined') {
    const _originalRequire = require;
    require = function(id) {
      if (shouldStub(id)) {
        return getStub(id);
      }
      try {
        return _originalRequire.apply(this, arguments);
      } catch (e) {
        if (shouldStub(id)) {
          return getStub(id);
        }
        throw e;
      }
    };
    
    // Make it non-configurable if possible
    try {
      Object.defineProperty(require, 'cache', {
        get: function() { return requireCache; },
        configurable: true
      });
    } catch(e) {}
  }
  
  // Override in global/window if they exist
  if (typeof global !== 'undefined') {
    global.require = require;
  }
  if (typeof window !== 'undefined') {
    window.require = require;
  }
  
  // Also patch __commonJS if it exists (esbuild's wrapper)
  const originalCommonJS = typeof __commonJS !== 'undefined' ? __commonJS : null;
  if (originalCommonJS) {
    __commonJS = function(cb, mod) {
      return function __require() {
        if (mod) return mod.exports;
        const result = originalCommonJS(cb, mod);
        // Check if the callback tries to require Node.js modules
        const cbStr = String(cb);
        if (nodeModulesToStub.some(m => cbStr.includes('"' + m + '"') || cbStr.includes("'" + m + "'"))) {
          return { exports: {} };
        }
        return result;
      };
    };
  }
})();
`;

const prod = (process.argv[2] === 'production');

// Node.js modules that should be stubbed out
const nodeModulesToStub = ['stream', 'readable-stream', 'fs', 'path', 'util', 'events', 'buffer', 'base64'];

// Plugin to replace Node.js module requires with empty objects
const nodeStubPlugin = {
  name: 'node-stub',
  setup(build) {
    // Intercept ALL imports/requires - check if they're Node.js modules
    // This must run first to catch everything
    build.onResolve({ filter: /.*/ }, args => {
      const firstPart = args.path.split('/')[0].split('@')[0]; // Handle scoped packages
      if (nodeModulesToStub.includes(firstPart) || nodeModulesToStub.includes(args.path)) {
        return { path: args.path, namespace: 'node-stub' };
      }
      return null;
    });
    
    // Also intercept when loading files that might require Node.js modules
    build.onLoad({ filter: /readable-stream-browser\.js$/ }, args => {
      // Replace the require("stream") in readable-stream-browser.js with our stub
      return {
        contents: 'module.exports = {};',
        loader: 'js',
      };
    });
    
    // Provide empty stub content for Node.js modules
    build.onLoad({ filter: /.*/, namespace: 'node-stub' }, args => {
      return {
        contents: 'module.exports = {};',
        loader: 'js',
      };
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['main.ts'],
  bundle: true,
  platform: 'browser',
  plugins: [nodeStubPlugin],
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins
  ],
  format: 'cjs',
  target: 'es2020',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  mainFields: ['browser', 'module', 'main'],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
